---
- name: make a build dir
  file: state=directory name=/root/oracle-java-8-dockerized

- name: put Dockerfile
  template: src=Dockerfile dest=/root/oracle-java-8-dockerized/Dockerfile

- name: build a Docker image for Oracle Java 8
  command: docker build -t gitinsky/oracle-java-8:0.1.7 --rm /root/oracle-java-8-dockerized

- name: tag it as latest
  command: docker build -t gitinsky/oracle-java-8:latest --rm /root/oracle-java-8-dockerized
