FROM gitinsky/baseimage:0.1.4
MAINTAINER Git In Sky <support@gitinsky.com>

RUN apt-get update && apt-get install wget && wget http://ns2.1888.spb.ru/jdk-8u31-linux-x64.tar.gz && tar xzf /jdk-8u31-linux-x64.tar.gz && rm /jdk-8u31-linux-x64.tar.gz
